GROQ_API_KEY = "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"
MODEL_NAME = "llama3-8b-8192"

[mongodb]
uri = "mongodb+srv://Praneesh:Prawns(101)!@cluster0.gsn128t.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"